---

- name: Import Adapta GPG signing key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
    id: 2D87398A
  when: ansible_os_family == 'Debian'
  tags:
    - adapta

- name: Add Adapta repository
  apt_repository:
    repo: "deb http://ppa.launchpad.net/tista/adapta/ubuntu {{ansible_distribution_release | lower}} main"
    state: present
  when: ansible_os_family == 'Debian'
  tags:
    - adapta

- name: Install Adapta packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - adapta-gtk-theme
    - adapta-backgrounds
  when: ansible_os_family == 'Debian'
  tags:
    - adapta

- name: Install Unity Tweak Tool packages
  apt:
    name: unity-tweak-tool
    state: present
  when: ansible_distribution == 'Ubuntu'
  tags:
    - adapta
